[build]
  command = "echo 'No build required'"
  functions = "netlify/functions"
  publish = "."

# [build.environment]
  # NODE_VERSION = "18"
  # NPM_FLAGS = "--production=false"

[[headers]]
  for = "/.netlify/functions/*"  # 匹配所有云函数
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Content-Security-Policy = "default-src 'self'; script-src 'self' https://trusted.cdn.com"

# [functions]
  # 设置函数超时时间
  # timeout = 10
  # 日志保留设置
  # node_bundler = "esbuild"